name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_and_coverage:
    name: Run Tests and Generate Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'  # Specify your Node.js version here

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV

      - name: Cache Yarn directory
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install


      - name: Run tests and generate coverage
        run: npx hardhat coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
