name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Gas-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install HardHat
        run: npm i hardhat

      - name: Run gas tests and generate report
        id: gas_test
        run: npx hardhat test
        env:
          BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_API_KEY }}
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
          outputFile: gasReporterOutput.json
        continue-on-error: true

      - name: Extract JSON report from file
        id: extract_report
        run: |
          echo "Reading JSON report from file..."
          json_report=$(cat gasReporterOutput.json)
          echo "::set-output name=report::$json_report"

      - name: Convert JSON to Markdown
        id: table
        uses: buildingcash/json-to-markdown-table-action@v1
        with:
          json: ${{ steps.extract_report.outputs.report }}

      - name: Comment PR with Gas Test Report
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            # Gas Test Report 📊
            The gas test results are as follows:

            ${{ steps.table.outputs.table }}

  Coverage-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install HardHat
        run: npm i hardhat

      - name: Run tests and generate coverage
        run: npx hardhat coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
