name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Gas-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install HardHat
        run: npm i hardhat

      - name: Run gas tests and generate report
        id: gas_test
        run: npx hardhat test
        env:
          BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_API_KEY }}
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}

      - name: Generate Markdown Table
        run: node parseGasReport.js

      - name: Read Markdown Table
        id: filter_gas_report
        run: echo "::set-output name=gas_report::$(cat md_gas_report.txt)"

      - name: Comment PR with Gas Test Report
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            # Gas Test Report 📊
            The gas test results are as follows:
            ${{ steps.filter_gas_report.outputs.gas_report }}

  Coverage-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install HardHat
        run: npm i hardhat

      - name: Run tests and generate coverage
        run: npx hardhat coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
