name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Gas-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install HardHat
        run: npm i hardhat

      - name: Run gas tests
        run: npx hardhat test
        env:
          BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_API_KEY }}
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
          CI: true

      - name: Display JSON contents
        run: cat gasReporterOutput.json

      - name: PR comment with Markdown file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: gasReporterOutput.json
          comment_tag: gas_test_output

  Coverage-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install HardHat
        run: npm i hardhat

      - name: Run tests and generate coverage
        run: npx hardhat coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
